######################################################################
##
## Filename: sine_reader.udo
## Created on: Tue Feb 19 9:36:29 PM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
